const estadosCiviles = ["Soltero/a", "Casado/a", "Divorciado/a", "Viudo/a"];
const parentescos = ["Cónyuge", "Concubina/o", "Hijo/a"];
const presion = [
  "Menos de 1 año",
  "1 año",
  "2 años",
  "3 años",
  "4 años",
  "5 años",
  "6 años",
  "7 años",
  "8 años",
  "9 años",
  "10 años o más",
];
const cantidadFuma = [
  "1 a 5 cigarrillos",
  "6 a 10 cigarrillos",
  "11 a 20 cigarrillos",
  "Más de 20 cigarrillos",
];

const paises = [
  "Afganistán",
  "Albania",
  "Alemania",
  "Andorra",
  "Angola",
  "Antigua y Barbuda",
  "Arabia Saudita",
  "Argelia",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaiyán",
  "Bahamas",
  "Bangladés",
  "Baréin",
  "Barbados",
  "Bélgica",
  "Belice",
  "Benín",
  "Bielorrusia",
  "Birmania",
  "Bolivia",
  "Bosnia y Herzegovina",
  "Botsuana",
  "Brasil",
  "Brunéi",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Bután",
  "Cabo Verde",
  "Camboya",
  "Camerún",
  "Canadá",
  "Catar",
  "Chad",
  "Chile",
  "China",
  "Chipre",
  "Ciudad del Vaticano",
  "Colombia",
  "Comoras",
  "Corea del Norte",
  "Corea del Sur",
  "Costa de Marfil",
  "Costa Rica",
  "Croacia",
  "Cuba",
  "Dinamarca",
  "Dominica",
  "Ecuador",
  "Egipto",
  "El Salvador",
  "Emiratos Árabes Unidos",
  "Eritrea",
  "Eslovaquia",
  "Eslovenia",
  "España",
  "Estados Unidos",
  "Estonia",
  "Esuatini",
  "Etiopía",
  "Filipinas",
  "Finlandia",
  "Francia",
  "Gabón",
  "Gambia",
  "Georgia",
  "Ghana",
  "Granada",
  "Grecia",
  "Guatemala",
  "Guinea",
  "Guinea-Bisáu",
  "Guinea Ecuatorial",
  "Guyana",
  "Haití",
  "Honduras",
  "Hungría",
  "India",
  "Indonesia",
  "Irak",
  "Irán",
  "Irlanda",
  "Islandia",
  "Islas Marshall",
  "Islas Salomón",
  "Israel",
  "Italia",
  "Jamaica",
  "Japón",
  "Jordania",
  "Kazajistán",
  "Kenia",
  "Kirguistán",
  "Kiribati",
  "Kuwait",
  "Laos",
  "Lesoto",
  "Letonia",
  "Líbano",
  "Liberia",
  "Libia",
  "Liechtenstein",
  "Lituania",
  "Luxemburgo",
  "Madagascar",
  "Malasia",
  "Malaui",
  "Maldivas",
  "Malí",
  "Malta",
  "Marruecos",
  "Mauricio",
  "Mauritania",
  "México",
  "Micronesia",
  "Moldavia",
  "Mónaco",
  "Mongolia",
  "Montenegro",
  "Mozambique",
  "Namibia",
  "Nauru",
  "Nepal",
  "Nicaragua",
  "Níger",
  "Nigeria",
  "Noruega",
  "Nueva Zelanda",
  "Omán",
  "Países Bajos",
  "Pakistán",
  "Palaos",
  "Panamá",
  "Papúa Nueva Guinea",
  "Paraguay",
  "Perú",
  "Polonia",
  "Portugal",
  "Reino Unido",
  "República Centroafricana",
  "República Checa",
  "República del Congo",
  "República Democrática del Congo",
  "República Dominicana",
  "Ruanda",
  "Rumanía",
  "Rusia",
  "San Cristóbal y Nieves",
  "San Marino",
  "San Vicente y las Granadinas",
  "Santa Lucía",
  "Santo Tomé y Príncipe",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leona",
  "Singapur",
  "Siria",
  "Somalia",
  "Sri Lanka",
  "Sudáfrica",
  "Sudán",
  "Sudán del Sur",
  "Suecia",
  "Suiza",
  "Surinam",
  "Tailandia",
  "Tanzania",
  "Tayikistán",
  "Timor Oriental",
  "Togo",
  "Tonga",
  "Trinidad y Tobago",
  "Túnez",
  "Turkmenistán",
  "Turquía",
  "Tuvalu",
  "Ucrania",
  "Uganda",
  "Uruguay",
  "Uzbekistán",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Yibuti",
  "Zambia",
  "Zimbabue",
];

const provincias = [
  "CABA",
  "Buenos Aires",
  "Catamarca",
  "Chaco",
  "Chubut",
  "Córdoba",
  "Corrientes",
  "Entre Ríos",
  "Formosa",
  "Jujuy",
  "La Pampa",
  "La Rioja",
  "Mendoza",
  "Misiones",
  "Neuquén",
  "Río Negro",
  "Salta",
  "San Juan",
  "San Luis",
  "Santa Cruz",
  "Santa Fe",
  "Santiago del Estero",
  "Tierra del Fuego",
  "Tucumán",
];

const tipoDoc = [
  "DNI",
  "Pasaporte",
  "Libreta de Enrolamiento",
  "Libreta Cívica",
  "Otro",
];

const formFields = [
  // Datos personales
  {
    name: "nombre",
    label: "Apellido y Nombre",
    type: "text",
    xs: 12,
    sm: 5,
    md: 5,
    required: true,
    maxLength: 100,
  },
  {
    name: "fechaNac",
    label: "Fecha de Nacimiento",
    type: "date",
    xs: 12,
    sm: 3,
    md: 3,
    required: true,
  },
  {
    name: "tipoDoc",
    label: "Tipo de Documento",
    type: "select",
    options: tipoDoc,
    xs: 12,
    sm: 4,
    md: 4,
    required: true,
  },
  {
    name: "dni",
    label: "DNI",
    type: "text",
    xs: 12,
    sm: 2,
    md: 2,
    required: true,
    maxLength: 8,
  },
  {
    name: "sexo",
    label: "Sexo",
    type: "select",
    options: ["F", "M"],
    xs: 12,
    sm: 1.5,
    md: 1.5,
    required: true,
  },
  {
    name: "nacionalidad",
    label: "Nacionalidad",
    type: "select",
    options: paises,
    xs: 12,
    sm: 4,
    md: 4,
    required: true,
  },
  {
    name: "estadoCivil",
    label: "Estado civil",
    type: "select",
    options: estadosCiviles,
    xs: 12,
    sm: 4.5,
    md: 4.5,
    required: true,
  },

  {
    name: "calle",
    label: "Calle",
    type: "text",
    xs: 12,
    sm: 6,
    md: 6,
    required: true,
    maxLength: 20,
  },
  {
    name: "numero",
    label: "Nº",
    type: "text",
    xs: 12,
    sm: 2,
    md: 2,
    required: true,
    maxLength: 10,
  },
  {
    name: "piso",
    label: "Piso",
    type: "text",
    xs: 12,
    sm: 2,
    md: 2,
    maxLength: 5,
  },
  {
    name: "dto",
    label: "Dto",
    type: "text",
    xs: 12,
    sm: 2,
    md: 2,
    maxLength: 5,
  },
  {
    name: "entreCalles",
    label: "Entre calles",
    type: "text",
    xs: 12,
    sm: 6,
    md: 6,
    maxLength: 20,
  },
  {
    name: "tel1",
    label: "Tel. 1",
    type: "text",
    xs: 12,
    sm: 3,
    md: 3,
    required: true,
    maxLength: 20,
  },
  {
    name: "tel2",
    label: "Tel. 2",
    type: "text",
    xs: 12,
    sm: 3,
    md: 3,
    maxLength: 20,
  },
  {
    name: "localidad",
    label: "Localidad",
    type: "text",
    xs: 12,
    sm: 6,
    md: 6,
    required: true,
    maxLength: 20,
  },
  {
    name: "cp",
    label: "C.P.",
    type: "text",
    xs: 12,
    sm: 2,
    md: 2,
    required: true,
    maxLength: 5,
  },
  {
    name: "provincia",
    label: "Provincia",
    type: "select",
    options: provincias,
    xs: 12,
    sm: 4,
    md: 4,
    required: true,
  },
  {
    name: "claveFiscal",
    label: "Clave Fiscal",
    type: "password",
    xs: 12,
    sm: 4,
    md: 4,
    required: true,
    maxLength: 20,
  },
  {
    name: "email",
    label: "Email",
    type: "email",
    xs: 12,
    sm: 8,
    md: 8,
    maxLength: 50,
  },

  // Datos empresa
  {
    name: "empresa",
    label: "Nombre (Empresa)",
    type: "text",
    xs: 12,
    sm: 5,
    md: 5,
    maxLength: 50,
  },
  {
    name: "cuitEmpresa",
    label: "CUIT (Empresa)",
    type: "text",
    xs: 12,
    sm: 3,
    md: 3,
    maxLength: 11,
  },
  {
    name: "calleEmpresa",
    label: "Calle (Empresa)",
    type: "text",
    xs: 12,
    sm: 4,
    md: 4,
    maxLength: 20,
  },
  {
    name: "localidadEmpresa",
    label: "Localidad (Empresa)",
    type: "text",
    xs: 12,
    sm: 6,
    md: 6,
    maxLength: 20,
  },
  {
    name: "cpEmpresa",
    label: "C.P. (Empresa)",
    type: "text",
    xs: 12,
    sm: 2.5,
    md: 2.5,
    maxLength: 5,
  },
  {
    name: "provinciaEmpresa",
    label: "Provincia (Empresa)",
    type: "select",
    options: provincias,
    xs: 12,
    sm: 3.5,
    md: 3.5,
  },

  // Salud
  {
    name: "presionAlta",
    label: "¿Tuvo presión alta?",
    type: "checkbox",
    xs: 12,
    sm: 4,
    md: 4,
  },
  {
    name: "presionAltaDesde",
    label: "¿Hace cuánto?",
    type: "select",
    options: presion,
    xs: 12,
    sm: 8,
    md: 8,
    dependsOn: "presionAlta",
    required: true,
  },
  { name: "fuma", label: "¿Fuma?", type: "checkbox", xs: 12, sm: 4, md: 4 },
  {
    name: "cantFuma",
    label: "¿Cuántos por día?",
    type: "select",
    options: cantidadFuma,
    xs: 12,
    sm: 8,
    md: 8,
    dependsOn: "fuma",
    required: true,
  },
  {
    name: "diabetes",
    label: "¿Tiene diabetes?",
    type: "checkbox",
    xs: 12,
    sm: 4,
    md: 4,
  },
  {
    name: "diabetesDesde",
    label: "¿Desde cuándo?",
    type: "date",
    xs: 12,
    sm: 8,
    md: 8,
    dependsOn: "diabetes",
    required: true,
  },
  {
    name: "operaciones",
    label: "¿Tuvo alguna operación?",
    type: "checkbox",
    xs: 12,
    sm: 4,
    md: 4,
  },
  {
    name: "operacionesCuales",
    label: "¿Cuáles?",
    type: "text",
    xs: 12,
    sm: 8,
    md: 8,
    dependsOn: "operaciones",
    maxLength: 100,
  },
  {
    name: "medicamentos",
    label: "¿Toma algún medicamento?",
    type: "checkbox",
    xs: 12,
    sm: 4,
    md: 4,
  },
  {
    name: "medicamentosCuales",
    label: "¿Cuáles?",
    type: "text",
    xs: 12,
    sm: 8,
    md: 8,
    dependsOn: "medicamentos",
    maxLength: 100,
  },
  {
    name: "alergiasMedicamentos",
    label: "¿Es alérgico a medicamentos?",
    type: "checkbox",
    xs: 12,
    sm: 4,
    md: 4,
  },
  {
    name: "alergiasMedicamentosCuales",
    label: "¿Cuáles?",
    type: "text",
    xs: 12,
    sm: 8,
    md: 8,
    dependsOn: "alergiasMedicamentos",
    maxLength: 100,
    required: true,
  },
  {
    name: "observaciones",
    label: "Observaciones",
    type: "textarea",
    xs: 12,
    sm: 12,
    md: 12,
    maxLength: 500,
  },
  {
    name: "asesor",
    label: "Nombre asesor",
    type: "text",
    xs: 12,
    sm: 12,
    md: 12,
    required: true,
    maxLength: 30,
  },
];

export { estadosCiviles, parentescos, formFields };
